import{S as y,i as c}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const l={formEl:document.querySelector(".search-form"),galleryEl:document.querySelector(".gallery-box"),btnEl:document.querySelector(".search-btn")},a=document.querySelector(".loader-box");l.formEl.addEventListener("submit",p);l.formEl.addEventListener("input",s=>{l.formEl.elements.word.value.trim()&&(l.btnEl.disabled=!1)});function p(s){s.preventDefault(),a.classList.remove(".is-hiden");const r=document.querySelector(".gallery");r&&r.remove();const i='<div class="gallery"></div>';l.galleryEl.insertAdjacentHTML("afterbegin",i);const o=s.target.elements.word.value.trim();o?h(o).then(e=>{let t=e.hits;t.length>0?(a.classList.add(".is-hiden"),b(t),new y(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()):(a.classList.add(".is-hiden"),c.show({timeout:5e3,position:"topCenter",color:"#d11804",messageColor:"white",titleColor:"#FFFFFF",iconColor:"#FFFFFF",message:"Sorry, there are no images matching your search query. Please try again!"}))}):(a.classList.add(".is-hiden"),c.show({timeout:5e3,position:"topCenter",color:"#d11804",messageColor:"white",titleColor:"#FFFFFF",iconColor:"#FFFFFF",message:"The field is empty. Please enter a word!"})),l.formEl.reset(),l.btnEl.disabled=!0}function h(s){const r="https://pixabay.com",i="/api/",o=`?key=42153044-59e7d8487fc2c2f8c6f74878d&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`,e=r+i+o;return fetch(e).then(t=>t.json())}function b(s){const r=s.map(o=>{const{id:e,largeImageURL:t,webformatURL:n,tags:d,likes:m,views:f,comments:u,downloads:g}=o;return`<a class="gallery-link" href="${t}">
          <div class="gallery-item" id="${e}">
            <img class="gallery-image" src="${n}" alt="${d}" loading="lazy" data-source="${t}"/>
            <div class="info">
              <p class="info-item"><b>Likes</b>${m}</p>
              <p class="info-item"><b>Views</b>${f}</p>
              <p class="info-item"><b>Comments</b>${u}</p>
              <p class="info-item"><b>Downloads</b>${g}</p>
            </div>
          </div>
        </a>`}).join("");l.galleryEl.querySelector(".gallery").insertAdjacentHTML("beforeend",r)}
//# sourceMappingURL=commonHelpers.js.map
